
  

server:
  port: 8085

spring:
   application:
    name: API-Gateway
   cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: Product-Service
        uri: http://localhost:8081/
        predicates:
        - Path=/product/**
      - id: User-Service
        uri: http://localhost:8082/
        predicates:
        - Path=/api/**
      - id: Order-Service
        uri: http://localhost:8084/
        predicates:
        - Path=/order/**
      
